name: Autosave Codespace Changes

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action every day at midnight

jobs:
  save_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Commit and Push Changes if Modified
      run: |
        git add -A
        git diff-index --quiet HEAD || git commit -m "Autosave changes from Codespace"
        git push
